version: '3'

services:
  goa:
    container_name: goa
    build:
      context: $GOPATH/src/github.com/ebalkanski/goa
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - "$GOPATH/src/github.com/ebalkanski/goa:/go/src/github.com/ebalkanski/goa"
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db
    restart: always