swagger: "2.0"
info:
  title: Play with goa
  description: HTTP service for playing with goa
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /user:
    post:
      tags:
      - user
      summary: create user
      description: Create new user.
      operationId: user#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserCreateRequestBody'
          required:
          - name
          - age
      responses:
        "201":
          description: User is created successfully.
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/UserCreateBadRequestResponseBody'
            required:
            - message
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserCreateInternalServerErrorResponseBody'
            required:
            - message
      schemes:
      - http
  /user/{name}:
    get:
      tags:
      - user
      summary: get user
      operationId: user#get
      parameters:
      - name: name
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserGetResponseBody'
            required:
            - name
            - age
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/UserGetBadRequestResponseBody'
            required:
            - message
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserGetInternalServerErrorResponseBody'
            required:
            - message
      schemes:
      - http
definitions:
  UserCreateBadRequestResponseBody:
    title: UserCreateBadRequestResponseBody
    type: object
    properties:
      message:
        type: string
        example: error
    example:
      message: error
    required:
    - message
  UserCreateInternalServerErrorResponseBody:
    title: UserCreateInternalServerErrorResponseBody
    type: object
    properties:
      message:
        type: string
        example: error
    example:
      message: error
    required:
    - message
  UserCreateRequestBody:
    title: UserCreateRequestBody
    type: object
    properties:
      age:
        type: integer
        example: 25
        format: int64
      name:
        type: string
        example: Bob
    example:
      age: 25
      name: Bob
    required:
    - name
    - age
  UserGetBadRequestResponseBody:
    title: UserGetBadRequestResponseBody
    type: object
    properties:
      message:
        type: string
        example: error
    example:
      message: error
    required:
    - message
  UserGetInternalServerErrorResponseBody:
    title: UserGetInternalServerErrorResponseBody
    type: object
    properties:
      message:
        type: string
        example: error
    example:
      message: error
    required:
    - message
  UserGetResponseBody:
    title: UserGetResponseBody
    type: object
    properties:
      age:
        type: integer
        example: 25
        format: int64
      name:
        type: string
        example: Bob
    example:
      age: 25
      name: Bob
    required:
    - name
    - age
