openapi: 3.0.3
info:
  title: Calculator Service
  description: HTTP service for adding numbers, a goa teaser
  version: "1.0"
servers:
- url: http://localhost:8080
paths:
  /add/{a}/{b}:
    get:
      tags:
      - calc
      summary: add calc
      operationId: calc#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 1
          format: int64
        example: 1
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 2
          format: int64
        example: 2
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 3
                format: int64
              example: 3
  /rate/{id}:
    post:
      tags:
      - calc
      summary: rate calc
      operationId: calc#rate
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          example: 1
          format: int64
        example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                a: 1.1
                b: 2.2
              additionalProperties: true
            example:
              a: 1.1
              b: 2.2
      responses:
        "204":
          description: No Content response.
components: {}
