swagger: "2.0"
info:
  title: Play with goa
  description: HTTP service for playing with goa
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /add/{a}/{b}:
    get:
      tags:
      - play
      summary: add play
      operationId: play#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /rate/{id}:
    post:
      tags:
      - play
      summary: rate play
      operationId: play#rate
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      - name: map
        in: body
        required: true
        schema:
          type: object
          additionalProperties: true
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
