swagger: "2.0"
info:
  title: Calculator Service
  description: HTTP service for adding numbers, a goa teaser
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /add/{a}/{b}:
    get:
      tags:
      - calc
      summary: add calc
      operationId: calc#add
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/CalcAddDivByZeroResponseBody'
            required:
            - errors
      schemes:
      - http
  /rate/{id}:
    post:
      tags:
      - calc
      summary: rate calc
      operationId: calc#rate
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      - name: map
        in: body
        required: true
        schema:
          type: object
          additionalProperties: true
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
definitions:
  CalcAddDivByZeroResponseBody:
    title: CalcAddDivByZeroResponseBody
    type: object
    properties:
      errors:
        type: array
        items:
          type: string
          example: Magnam asperiores dolorum.
        description: division by zero leads to infinity.
        example:
        - Err1
        - Err2
    description: DivByZero is the error returned by the service methods when the right
      operand is 0.
    example:
      errors:
      - Err1
      - Err2
    required:
    - errors
