openapi: 3.0.3
info:
  title: Play with goa
  description: HTTP service for playing with goa
  version: "1.0"
servers:
- url: http://localhost:8080
paths:
  /user:
    post:
      tags:
      - user
      summary: create user
      description: Create new user.
      operationId: user#create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              age: 25
              name: Bob
      responses:
        "201":
          description: User is created successfully.
  /user/{name}:
    get:
      tags:
      - user
      summary: get user
      operationId: user#get
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
          example: Bob
        example: Bob
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                age: 25
                name: Bob
components:
  schemas:
    User:
      type: object
      properties:
        age:
          type: integer
          example: 112266298297454489
          format: int64
        name:
          type: string
          example: Sit incidunt occaecati omnis nam omnis suscipit.
      example:
        age: 25
        name: Bob
      required:
      - name
      - age
